- .editorconfig
- together_bot/bot.py
Add ping commend with mention like `@bot ping`
> add ping commend when bot mentioned

- together_bot/bot.py
새 멤버가 길드에 입장하면 해당 멤버에게 'player' 역할을 추가합니다.
'play together'에서 일반 회원같은 역할인 'player'를 관리자가 추가하는 귀찮음을 줄여주기 위해 만듦.
> feature add: add role "player" when new member join the guild

- poetry.lock
- together_bot/bot.py
- together_bot/role.py
- Update dependencies
- fix: `repo` command returns wrong text
- add error handling when create role
> Feature: Add error handling when create role

- logging.yml
- poetry.lock
- pyproject.toml
- together_bot/bot.py
- together_bot/role.py
- add package pyyaml for read yaml file
- create logging config file 'logging.yml'
- load logging config file at the beginning of bot.py
- convert all print() usages to logging
> Convert print() to logging

- together_bot/bot.py
- together_bot/channel.py
- together_bot/role.py
- 개발되지 않은 명령어는 brief=TBD로 통일함.
- help 명령으로 접근할 때 출력되는 순서에 맞춰서 brief->help 순으로
통일함.
> add attributes brief and help to all commands

- together_bot/bot.py
- together_bot/role.py
- Update help message for `role get`
- Move cog setup call into setup func 
Close #17
> Update help message, fix minor issues

- together_bot/bot.py
- together_bot/role.py
> Fix commit history for #21

- Dockerfile
- README.md
https://github.com/team-play-together/together-bot/pull/22
이전 pull request 요구사항 반영 및 새로운 포크 저장소에서 작업
> Update: Dockerfile 및 README 도커 명령어 추가

- .devcontainer/devcontainer.json
- .editorconfig
- .vscode/extensions.json
- .vscode/settings.json
- README.md
- poetry.lock
- together_bot/bot.py
- together_bot/channel.py
- together_bot/commands.py
- together_bot/role.py
- together_bot/time.py
-  Use isort, Add type annotation 
-  Update README to add poetry `in-project` config 
- Bump up
>  Use isort, Add type annotation 

- Dockerfile
- pyproject.toml
> Update to python 3.9

- .github/workflows/lint.yml
> Add isort action into github action

- .env.example
- poetry.lock
- pyproject.toml
- together_bot/bot.py
- together_bot/weather.py
`weather current [city]`: Get current city weather that matches name.
If no given city name, default value is "Seoul"
> Add weather command using OpenWeather API

- together_bot/fword.py
- 파일 경로를 fword.py 기준 상대 경로로 지정
> 비속어 리스트를 Heroku에서 불러오지 못하는 오류 수정

- poetry.lock
- pyproject.toml
- together_bot/time.py
* time now 명령어가 NTP 서버에서 시간을 가져오도록 수정(근데 내가 이걸 왜 수정하려고 했는지 기억 안남)
* time convert가 KST를 입력받는데 UTC로 간주하고 시간을 변환해서 잘못된 세계시간이 출력되는 오류를 수정함.
> time now 명령어가 NTP 서버를 통해 시간을 가져오도록 수정, time convert의 출력 오류 수정

- Dockerfile
- together_bot/bot.py
- together_bot/fword.py
> fword_list의 경로를 수정

- .env.example
- together_bot/commands.py
나무위키 검색 커맨드
% -> %25
\  -> %5C
공백 -> %20
> add namu command

- .github/workflows/lint.yml
- poetry.lock
- pyproject.toml
해당되는 dependency
* black
* isort
~~거대한 똥을 치우러 왔다~~
이 개똥PR와 관련된 PR 목록
#61 #60 #59 #58 #56
> github action lint와 project dependency을 맞춤

- README.md
- docker-compose.dev.yml
- docker-compose.yml
README에 적힌 명령어에 대해서 테스트 후 적용
- image build 확인
- container 생성 확인
- 서비스 실행 후 attach 확인
- env-file 적용 확인
- -e 옵션 적용 확인
- bind volume mount 확인
- attach 된 tty 종료 후 container 제거 확인
> Docker compose 추가 및 README 수정

- tests/test_fword.py
- together_bot/fword.py
1. `Trie`에 대한 테스트
1.a. `__contains__ `테스트
1.b. `insert `테스트
1.c. `find_all_occurences `테스트
2. `fword` 명령어 내의 코드에서 테스트 할 거 있으면 추가
> fword test 추가

- poetry.lock
- pyproject.toml
pyyaml 메이저 번경이 문제라고 생각해서 봤으나, 현재 사용하고 있는 `safe_load` 함수와는 상관없는 부분에서 발생한 변경
Related #90 #94 #95 #101 #103
> Bump up dependencies

- poetry.lock
- pyproject.toml
전체적인 의존성 업데이트.
개발의존성 위주 업데이트와 isort 설정 변경을 포함
> 의존성 버전 업, pre-commit은 개발 의존성으로 변경
